[Service]
ExecStartPre=/usr/bin/mkdir -p %h/.cache/restic-tmp
Environment=TMPDIR=%h/.cache/restic-tmp
ExecStart=
ExecStart=/usr/bin/systemd-inhibit --what=shutdown --who=backup-task --why="restic backup running" /usr/bin/resticprofile --no-prio --no-ansi --config %h/.local/share/backup/restic/profiles.toml run-schedule backup@default
