version = "1"
prevent-sleep = true
[default]
env-file = "$HOME/.config/restic/env"
lock-wait = "10m"
password-file = "$HOME/.config/restic/password"
repository = "s3:fra1.digitaloceanspaces.com/mwmbackups"
[default.backup]
compression = "max"
exclude-if-present = [".resticignore", ".nobackup", ".backupignore"]
one-file-system = true
run-before = "/usr/bin/podman pause --all;$HOME/.local/share/backup/restic/hooks/export-layered-packages.sh && $HOME/.local/share/backup/restic/hooks/export-flatpaks.sh && $HOME/.local/share/backup/restic/hooks/export-vscode-extensions.sh"
run-finally = "/usr/bin/podman unpause --all"
schedule = "*:0/30"
schedule-permission = "user_logged_on"
source = ["$HOME"]

exclude = [
  "$HOME/.cache",
  "$HOME/.local/share/containers/storage",
  "$HOME/.local/share/Trash",
  "$HOME/**/node_modules",
  "$HOME/**/target",
]

[default.check]
read-data-subset = "30%"
schedule = "00/2:00:00"
schedule-permission = "user_logged_on"
[default.forget]
keep-daily = 7
keep-monthly = 12
keep-weekly = 4
prune = true
schedule = "12:00"
schedule-permission = "user_logged_on"

[default.restore]
delete = true
host = true
path = true
target = "/"
run-after = "$HOME/.local/share/backup/restore/bootstrap.sh"
