version = "1"
prevent-sleep = true
[default]
repository = "s3:fra1.digitaloceanspaces.com/mwmbackups"
password-file = "$HOME/.config/restic/password"
env-file = "$HOME/.config/restic/env"
run-before = "/usr/bin/podman pause --all;$HOME/.local/share/backup/restic/hooks/export-layered-packages.sh && $HOME/.local/share/backup/restic/hooks/export-flatpaks.sh && $HOME/.local/share/backup/restic/hooks/export-vscode-extensions.sh"
run-finally = "/usr/bin/podman unpause --all"
check-after = true
check-before = true
check-unused = true
[default.backup]
schedule = "*:0/30"
schedule-permission = "user_logged_on"
source = ["$HOME"]

exclude = [
  "$HOME/.cache",
  "$HOME/.local/share/containers/storage",
  "$HOME/.local/share/Trash",
  "$HOME/**/node_modules",
  "$HOME/**/target",
]

[default.prune]
schedule-permission = "user_logged_on"
schedule = "15/2:00:00"
[default.check]
schedule-permission = "user_logged_on"
schedule = "00/2:00:00"
read-data-subset = "30%"
[default.forget]
schedule = "12:00"
schedule-permission = "user_logged_on"
keep-daily = 7
keep-weekly = 4
keep-monthly = 12
prune = true
